### ISSUE TITLE
Vim(let):E117: Unknown function: ddu#ui_action

### ISSUE THREAD

**Issue by mikelue** [Shougo/ddu-source-action#1]
When I am using the "do" action, this plugin fires an exception
```
[denops] Error: Failed to call 'uiAction' with
...(ignore)
Error: Failed to call 'ddu#ui_action(default, itemAction, [object Object])':
Vim(let):E117: Unknown function: ddu#ui_action
[denops] function denops#api#vim#call[2]..ddu#item_action[1]..ddu#_request[22]..denops#request[1]..denops#server#request[4]..denops#_internal#server#chan#request[4]..denops#_internal#rpc#vim#request[1]..denops#api#vim#call, line 2
[denops]     at Vim.call (file:///home/mike/.vim/plugged/denops.vim/denops/@denops-private/host/vim.ts:37:13)
[denops]     at async Session.call (file:///home/mike/.vim/plugged/denops.vim/denops/@denops-private/service.ts:163:14)
[denops]     at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:99:12)
[denops]     at async https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:108:18
[denops]     at async Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:104:29)
...(ignore)
```

I guess, it is because of the renaming of function by [Shougo/ddu.vim](https://github.com/Shougo/ddu.vim)
```
2023.04.04
* Rename "ddu#ui_action()" to "ddu#ui_sync_action()".
* "ddu#ui#do_action()" executes action asynchronously.
```

- My ddu version: [5fa96a4a](https://github.com/Shougo/ddu.vim/commit/5fa96a4a7ec03a503ca7af35a8d40dd207b641e9)
- My ddu-source-action version: [3eb99878](https://github.com/Shougo/ddu-source-action/commit/3eb99878c3e5bc25b67421fd8f02ad6f74722a21)

Any comment would be appreciated.

**Comment by Shougo** [comment]
Fixed.
